bustrace:
  serviceKey: 1234567890
  routeId: 224000047
  scheduler:
    threadPoolSize: 5

logging:
  level:
    hello: INFO
    org:
      springframework:
        ws: DEBUG
        data:
          mongodb: DEBUG

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: bustrace
  mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp