bustrace:
  serviceKey: 1234567890
  routeId: 224000047
  scheduler:
    threadPoolSize: 5

server:
  port: 8080

logging:
  level:
    hello: INFO
    org:
      springframework:
        ws: INFO
        data:
          mongodb: INFO

spring:
  pid: bustrace.pid
  application:
    name: Bootstrap Spring Boot
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: bustrace
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://192.168.0.101:27017